framework:
    cache:
        app: cache.adapter.redis
        default_redis_provider: '%env(REDIS_URL)%'
        system: cache.adapter.system

        # Namespaced pools use the above "app" backend by default
        #pools:
            #my.dedicated.cache: null
